# Generated by Django 3.1.7 on 2021-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210424_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='name',
            field=models.CharField(default='Maincc', max_length=255, unique=True, verbose_name='Category name'),
        ),
    ]
