# Generated by Django 3.1.7 on 2021-04-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_maincategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(default='some', max_length=255, unique=True, verbose_name='Book category name'),
        ),
    ]
