# Generated by Django 3.1.7 on 2021-05-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210511_1019'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='bookdetail',
            managers=[
            ],
        ),
    ]
