# Generated by Django 3.1.7 on 2021-05-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210511_1034'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publisher',
            managers=[
            ],
        ),
    ]
