# Generated by Django 3.1.7 on 2021-05-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210511_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher city'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher country'),
        ),
    ]
