# Generated by Django 3.1.7 on 2021-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210511_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='genre',
            field=models.CharField(default='add genre', max_length=255, verbose_name='Book genre'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher address'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher name'),
        ),
    ]
