# Generated by Django 3.1.7 on 2021-05-14 21:23

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210515_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[utils.validators.validate_char_min_size], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default='999', verbose_name='Book price'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(default='No Data', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(default='No Data', max_length=255, unique=True),
        ),
    ]
