# Generated by Django 3.1.7 on 2021-05-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210515_0633'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='bookdetail',
        #     name='book_ptr',
        # ),
        # migrations.AddField(
        #     model_name='bookdetail',
        #     name='book',
        #     field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.book'),
        # ),
    ]
