# Generated by Django 3.1.7 on 2021-03-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группа задач'},
        ),
    ]
