# Generated by Django 3.1.7 on 2021-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_auto_20210424_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'customer'), (3, 'admin'), (2, 'manager')], default=1),
        ),
    ]
