# Generated by Django 3.1.7 on 2021-04-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0004_auto_20210424_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'customer'), (2, 'manager'), (3, 'admin')], default=1),
        ),
    ]
