# Generated by Django 3.1.7 on 2021-05-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0005_auto_20210424_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(3, 'admin'), (1, 'customer'), (2, 'manager')], default=1),
        ),
    ]
