# Generated by Django 3.1.7 on 2021-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0010_auto_20210511_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is_staff'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(3, 'admin'), (1, 'customer'), (2, 'manager')], default=1),
        ),
    ]
