# Generated by Django 3.1.7 on 2021-05-14 21:23

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0015_auto_20210515_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'customer'), (3, 'admin'), (2, 'manager')], default=1),
        ),
    ]
