# Generated by Django 3.1.7 on 2021-05-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0017_auto_20210515_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(2, 'manager'), (1, 'customer'), (3, 'admin')], default=1),
        ),
    ]
