# Generated by Django 3.1.7 on 2021-05-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0023_auto_20210515_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'customer'), (2, 'manager'), (3, 'admin')], default=1),
        ),
    ]
