# Generated by Django 3.1.7 on 2021-05-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0026_auto_20210515_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(2, 'manager'), (1, 'customer'), (3, 'admin')], default=1),
        ),
    ]
